# Copyright (C) 2019-2020 The Potato Open Sauce Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oppo//setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/oppo/CPH1859/proprietary/bin/kpoc_charger:system/bin/kpoc_charger \
    vendor/oppo/CPH1859/proprietary/bin/vtservice:system/bin/vtservice \
    vendor/oppo/CPH1859/proprietary/etc/init/init.vtservice.rc:system/etc/init/init.vtservice.rc \
    vendor/oppo/CPH1859/proprietary/etc/init/kpoc_charger.rc:system/etc/init/kpoc_charger.rc \
    vendor/oppo/CPH1859/proprietary/etc/permissions/privapp-permissions-mediatek.xml:system/etc/permissions/privapp-permissions-mediatek.xml \
    vendor/oppo/CPH1859/proprietary/framework/mediatek-ims-extension-plugin.jar:system/framework/mediatek-ims-extension-plugin.jar \
    vendor/oppo/CPH1859/proprietary/framework/mediatek-ims-legacy.jar:system/framework/mediatek-ims-legacy.jar \
    vendor/oppo/CPH1859/proprietary/lib/libcomutils.so:system/lib/libcomutils.so \
    vendor/oppo/CPH1859/proprietary/lib/libimsma.so:system/lib/libimsma.so \
    vendor/oppo/CPH1859/proprietary/lib/libimsma_adapt.so:system/lib/libimsma_adapt.so \
    vendor/oppo/CPH1859/proprietary/lib/libimsma_rtp.so:system/lib/libimsma_rtp.so \
    vendor/oppo/CPH1859/proprietary/lib/libimsma_socketwrapper.so:system/lib/libimsma_socketwrapper.so \
    vendor/oppo/CPH1859/proprietary/lib/libmtk_vt_service.so:system/lib/libmtk_vt_service.so \
    vendor/oppo/CPH1859/proprietary/lib/libmtk_vt_wrapper.so:system/lib/libmtk_vt_wrapper.so \
    vendor/oppo/CPH1859/proprietary/lib/libmtkaudio_utils.so:system/lib/libmtkaudio_utils.so \
    vendor/oppo/CPH1859/proprietary/lib/libmtkavenhancements.so:system/lib/libmtkavenhancements.so \
    vendor/oppo/CPH1859/proprietary/lib/libmtklimiter.so:system/lib/libmtklimiter.so \
    vendor/oppo/CPH1859/proprietary/lib/libmtkperf_client.so:system/lib/libmtkperf_client.so \
    vendor/oppo/CPH1859/proprietary/lib/libmtkshifter.so:system/lib/libmtkshifter.so \
    vendor/oppo/CPH1859/proprietary/lib/libshowlogo.so:system/lib/libshowlogo.so \
    vendor/oppo/CPH1859/proprietary/lib/libsignal.so:system/lib/libsignal.so \
    vendor/oppo/CPH1859/proprietary/lib/libsink.so:system/lib/libsink.so \
    vendor/oppo/CPH1859/proprietary/lib/libsource.so:system/lib/libsource.so \
    vendor/oppo/CPH1859/proprietary/lib/libsysenv_system.so:system/lib/libsysenv_system.so \
    vendor/oppo/CPH1859/proprietary/lib/libvcodec_cap.so:system/lib/libvcodec_cap.so \
    vendor/oppo/CPH1859/proprietary/lib/libvcodec_capenc.so:system/lib/libvcodec_capenc.so \
    vendor/oppo/CPH1859/proprietary/lib/libvt_avsync.so:system/lib/libvt_avsync.so \
    vendor/oppo/CPH1859/proprietary/lib/vendor.mediatek.hardware.mtkradioex@1.0.so:system/lib/vendor.mediatek.hardware.mtkradioex@1.0.so \
    vendor/oppo/CPH1859/proprietary/lib/vendor.mediatek.hardware.mms@1.0.so:system/lib/vendor.mediatek.hardware.mms@1.0.so \
    vendor/oppo/CPH1859/proprietary/lib/vendor.mediatek.hardware.mms@1.1.so:system/lib/vendor.mediatek.hardware.mms@1.1.so \
    vendor/oppo/CPH1859/proprietary/lib/vendor.mediatek.hardware.videotelephony@1.0.so:system/lib/vendor.mediatek.hardware.videotelephony@1.0.so \
    vendor/oppo/CPH1859/proprietary/lib64/libmtk-ril.so:system/lib64/libmtk-ril.so \
    vendor/oppo/CPH1859/proprietary/lib64/libmtk_vt_wrapper.so:system/lib64/libmtk_vt_wrapper.so \
    vendor/oppo/CPH1859/proprietary/priv-app/ImsService/lib/arm64/libmtk_vt_wrapper.so:system/priv-app/ImsService/lib/arm64/libmtk_vt_wrapper.so \
    vendor/oppo/CPH1859/proprietary/lib64/libmtkaudio_utils.so:system/lib64/libmtkaudio_utils.so \
    vendor/oppo/CPH1859/proprietary/lib64/libmtkavenhancements.so:system/lib64/libmtkavenhancements.so \
    vendor/oppo/CPH1859/proprietary/lib64/libmtklimiter.so:system/lib64/libmtklimiter.so \
    vendor/oppo/CPH1859/proprietary/lib64/libmtkperf_client.so:system/lib64/libmtkperf_client.so \
    vendor/oppo/CPH1859/proprietary/lib64/libmtkshifter.so:system/lib64/libmtkshifter.so \
    vendor/oppo/CPH1859/proprietary/lib64/libsysenv_system.so:system/lib64/libsysenv_system.so \
    vendor/oppo/CPH1859/proprietary/lib64/libvcodec_cap.so:system/lib64/libvcodec_cap.so \
    vendor/oppo/CPH1859/proprietary/lib64/libvcodec_capenc.so:system/lib64/libvcodec_capenc.so \
    vendor/oppo/CPH1859/proprietary/lib64/vendor.mediatek.hardware.mtkradioex@1.0.so:system/lib64/vendor.mediatek.hardware.mtkradioex@1.0.so \
    vendor/oppo/CPH1859/proprietary/lib64/vendor.mediatek.hardware.videotelephony@1.0.so:system/lib64/vendor.mediatek.hardware.videotelephony@1.0.so \
    vendor/oppo/CPH1859/proprietary/priv-app/ImsService/lib/arm64/vendor.mediatek.hardware.videotelephony@1.0.so:system/priv-app/ImsService/lib/arm64/vendor.mediatek.hardware.videotelephony@1.0.so \
    vendor/oppo/CPH1859/proprietary/product/etc/apns-conf.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/apns-conf.xml

PRODUCT_PACKAGES += \
    ImsService \
    mediatek-common \
    mediatek-framework \
    mediatek-ims-base \
    mediatek-ims-common \
    mediatek-telecom-common \
    mediatek-telephony-base \
    mediatek-telephony-common

PRODUCT_SOONG_NAMESPACES += \
    vendor/oppo/CPH1859
